### ISSUE TITLE
New sorted struct is not applied to inline structs

### ISSUE THREAD

**Issue by Gabri3l** [dkorunic/betteralign#3]
First of all thank you for your work on this! I noticed something that I'm not sure this tool will be able to address but thought I would bring this up. I have an easy way to reproduce the "issue".

```go
package main

import "net/http"

type MyStruct struct {
	Handler  http.HandlerFunc
	Method   string
	Pattern  string
	SomeUint uint16
	Resource string
}

func main() {
	register("3", MyStruct{
		func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(http.StatusOK)
		},
		http.MethodPost,
		"pattern",
		0,
		"resource",
	})
}

func register(version string, m MyStruct) error {
	return nil
}
```

The problem being that `MyStruct` gets optimally sorted but the inline struct maintains the previous order of fields which I then have to fix manually. Feel free to close this out if it's not something we can address, I might also take a look tonight and see if it's doable but wanted to let you know first.

**Comment by dkorunic** [comment]
@Gabri3l Right, it's well known and all previous tools are also having trouble with inline structs as it is quite, quite challenging (due to AST design and implementation decisions) to store reindexing actions for all sorted structs and apply that same reordering on every such inline struct later on. So it is doable, but it's rather challenging and I plan to tackle that but I don't have any exact timeframe for this.

**Comment by Gabri3l** [comment]
Makes sense! No rush at all on this and thank you for providing more context.

**Comment by dkorunic** [comment]
Right, for now what you can do is the following (in case you find manual inline struct reordering bothersome):
```
type MyStruct struct { //betteralign:ignore
	Handler  http.HandlerFunc
	Method   string
	Pattern  string
	SomeUint uint16
	Resource string
}
```
